seed: 42
dataset:
  name: tafeng
wandb:
  project: IMPORTANCE-AWARE-NBR
trainer:
  max_epochs: 40
  eval_every: 3
model:
  dim: 128
  num_heads: 4
  num_encoder_layers: 2
  num_gpt_layers: 2
  dropout: 0.3
  intent_dim: 32
optim:
  lr: 0.0004
  weight_decay: 0.001
  clip_norm: 1.0
batch_size: 128
max_seq_len: 30
num_workers: 8
